### ISSUE TITLE
AttributeError: type object 'Substance' has no attribute 'from_formula'

### ISSUE THREAD

**Issue by apthorpe** [bjodah/chempy#18]
While trying to replicate the sample application at http://hera.physchem.kth.se/~chempy/branches/master/examples/aqueous_radiolysis.html I installed a fresh copy of Anaconda (linux, x64), installed chempy via

    conda install -c https://conda.anaconda.org/bjodah chempy

and ran a slightly modified version of the radiolysis example code.

This failed with `AttributeError: type object 'Substance' has no attribute 'from_formula'` so I reduced the sample code to a minimal viable example (attached)

[c2.zip](https://github.com/bjodah/chempy/files/129889/c2.zip)

which is:

```python
from chempy.chemistry import Substance

_species = ['H', 'H+', 'H2', 'e-(aq)', 'HO2-', 'HO2', 'H2O2', 'HO3', 'O-', 'O2', 'O2-', 'O3', 'O3-', 'OH', 'OH-', 'H2O']

species = [Substance.from_formula(s) for s in _species]
```

Strangely, the later code which builds the `reactions` list of Reaction() objects from the `_reactions` dict seems to work, indicating that there is not a generic problem resolving method names in the `chempy.chemistry` namespace. The problem seems isolated to `chempy.chemistry.Substance`

Also, I was able to get this part of the sample code to work successfully using my distribution's stock python installation, though the sample code would fail later for other reasons which is why I installed Anaconda.

**Comment by apthorpe** [comment]
So this is a false alarm regarding the code; the problem is in the installation or documentation:

```
$ ls -l /opt/apthorpe/anaconda2/lib/python2.7/site-packages/chempy/chemistry.py /usr/local/lib/python2.7/dist-packages/chempy/chemistry.py    [15:03:56]
-rw-rw-r-- 2 apthorpe apthorpe 19806 Jan 26 09:05 /opt/apthorpe/anaconda2/lib/python2.7/site-packages/chempy/chemistry.py
-rw-r--r-- 1 root     staff    21214 Feb 13 16:22 /usr/local/lib/python2.7/dist-packages/chempy/chemistry.py
```

The package installed by conda is obsolete (see https://anaconda.org/bjodah/chempy ).

What is the proper method for installing chempy?

I'll defer trying to explain the problems I've had installing from source (involves incompatibilities with recent versions of numpy and pyodeint) until after trying the recommended installation method.

**Comment by bjodah** [comment]
@apthorpe thank you for reporting this. I simply hadn't pushed the build of the latest release yet, it should be there now. The build of the release is essentially automatic but I havn't automated the push of the build files yet.

I'm about to update the installation docs here:
https://github.com/bjodah/chempy/pull/17/files
(never mind the `python -m pytest --pyargs chempy` part, pytest from conda with Py2.7 seem to have a hard time finding installed packages for some reason).

Let me know if it works correctly for you now (I tried on a fresh miniconda2 install on a 64-bit Ubuntu 14.04 box).

I'm also interested in feedback in general and curious about your application in mind.

**Comment by apthorpe** [comment]
I just installed from the most recent source to anaconda and it worked with no problems. I'm still trying to verify the results look reasonable but there are no obvious problems.

chempy is a godsend for the problem I'm currently fighting with. I'm working on replicating results from several papers which look at radiolysis with variations in pH and radiation exposure so I was extremely interested in getting the sample aqueous radiolysis case working. I have been using the CHEMEQ2 solver http://www.dtic.mil/cgi-bin/GetTRDoc?AD=ADA392490 to estimate steady-state concentration of hydrogen gas due to radiolytic generation. As you can imagine, it's a stiff problem so while setting up the problem is straightforward, getting reasonable results can be difficult, requiring a lot of code tuning and experimentation.

If there's anything I can do to help with testing, documentation, etc, please let me know. I really appreciate that you've made this code available.

**Comment by apthorpe** [comment]
Also, I'm very curious where you got the reaction set for the radiolysis example; we're using the reactions listed in https://www.researchgate.net/publication/243349685_Model_for_radiolysis_of_water_and_aqueous_solutions_of_H-2_H2O2_and_O-2 which have some overlap with https://www.researchgate.net/publication/257432707_A_combined_experimental_and_model_analysis_on_the_effect_of_pH_and_O2aq_on_g-radiolytically_produced_H2_and_H2O2 On reviewing a few papers on the subject, there seems to be no rationale for which reactions are considered significant for modeling radiolysis. So far we've had inconsistent success replicating some of the published results and it's not clear if that's due to deficiencies in our software or in our choice of reaction set.

This isn't directly related to the initial bug report but these papers provide benchmark data for testing and validating chempy and may be of use to you.

**Comment by bjodah** [comment]
No worries about writing in this issue - it's a place as good as any (but it is open to the whole of internet so in case you want to contact me directly you are welcome to do so on my gmail address: bjodah).

I am glad to hear that you find ChemPy useful, especially since (or because of) the fact
that I've developed it as an underlying tool for studying chemical problems in radiation chemistry
(I felt the need for an abstraction layer that was easy to manipulate). Feel free to suggest improvements, I'll happily review suggested code inclusions too if you modify it in any way you think is useful for others.
The project is still quite young so things may change quite fast, but I try hard to deprecate things properly with at least on intermediate version before introducing any breaking changes.

I was actually not aware of CHEMEQ2, so thank you for the link. Is the program freely available? (it would be interesting to compare results). There seem to be quite a few codes around for modelling the deterministic "chemical stage" of radiolysis: FACSIMILE, Maksima chemist, supposedly a code named "Bora" (which I haven't been able to hunt down) and probably a few more. And then we have not even touched upon the early stages which involve Monte Carlo simulations of spur reactions.

Currently I am pursuing a PhD in chemistry at KTH, and my radiolysis modelling efforts are done under [Prof. Mats Jonsson](https://www.kth.se/en/che/divisions/tfk/staff/seniors/jonsson-1.79948)'s supervision. The reaction set in that notebook was actually generated from another Python library that I am writing which aims to collect models of (aqueous) radiolysis, and in this case the data is from [AECL report 153-127160-450](http://www.iaea.org/inis/collection/NCLCollectionStore/_Public/41/057/41057264.pdf) evaluated at 20 °C (with some minor changes of mine to make the radiolytic yields respect mass conservation). I intend to make the library collecting the models open source under the same permissive BSD-license within a couple of months in association with an article describing that and some modelling efforts of mine (including contributions from diffusion in systems with inhomogeneous radiation fields and/or surface reactions), and put it up here on github for easy of reuse, collaboration and collective validation.

I think that there is consensus around the core set of reactions in aqueous radiolysis, but yields and rate constants (especially at other than neutral pH values and temperatures far from room temperature) are subject of continuous review, many researchers in the field frequent the 
Miller Conference on Radiation Chemistry series and the Gordon conferences on Radiation Chemistry (which last time I heard, is to be replaced by another conference at BNL later this year).

Just out of curiousity: in what setting are you working on this project, academia or industry?
