### ISSUE TITLE
passing reaction params through to get_odesys

### ISSUE THREAD

**Issue by smsaladi** [bjodah/chempy#45]
In the process of setting up a system, I specify a `param` to reactions, but don't see them passed through when create the ODE. See below. I think I have misunderstood the API here. Could you lend a hand please?

```shell
In [56]: def mono_rev_single():
    ...:     '''Reversible mechanism with one central complex (pg 36)
    ...:     '''
    ...:     R1, R3 = sp.symbols('R_1 R_3')
    ...:
    ...:     # reactants and products
    ...:     E, A, P = map(Substance, ['E', 'A', 'P'])
    ...:
    ...:     # enzyme complexes
    ...:     X = Substance('X')
    ...:
    ...:     reactions = r1, r3 = [
    ...:         Equilibrium({'E', 'A'}, {'X'}, param=R1),
    ...:         Equilibrium({'X'}, {'E', 'P'}, param=R3)
    ...:     ]
    ...:     return ReactionSystem(reactions, (E, A, P, X))
    ...:

In [57]: rsys = mono_rev_single()

In [58]: rode = get_odesys(rsys)[0]

In [59]: rode.params
Out[59]: array([], dtype=object)

In [60]: rsys.params()
Out[60]: [R_1, R_3]

In [65]: rode = get_odesys(rsys, include_params=False)[0]

In [66]: rode.params
Out[66]: array([], dtype=object)

In [69]: print(rode.get_jac())
Matrix([[-R_1*y_1, -R_1*y_0, 0, R_3], [-R_1*y_1, -R_1*y_0, 0, 0], [0, 0, 0, R_3], [R_1*y_1, R_1*y_0, 0, -R_3]])
```

**Comment by bjodah** [comment]
@smsaladi thank you for reporting this. Since the ODE system will contain four reactions you need 4 parameters (currently you only provide 2 equilibrium constans). A `ReactionSystem` consisting of two equilibria cannot be described by an ODE system, but rather a nonlinear system of equations (thermodynamics vs. kinetics).

So we need to specify (at least one) rate constants and write the equilibria as a forward and backward reactions, here is an initial attempt by me:
```
In [1]: import sympy as sp
fr
In [2]: from chempy.chemistry import Substance, Equilibrium, ReactionSystem
f
In [3]: from chempy.kinetics.ode import get_odesys

In [4]: def mono_rev_single():
   ...:     '''Reversible mechanism with one central complex (pg 36)
   ...:     '''
   ...:     R1, R3, R1f, R3f = sp.symbols('R_1 R_3 R_1f R_3f')
   ...:     E, A, P, X = map(Substance, 'EAPX')
   ...:     equilibria = e1, e3 = [
   ...:         Equilibrium({'E', 'A'}, {'X'}, param=R1),
   ...:         Equilibrium({'X'}, {'E', 'P'}, param=R3)
   ...:     ]
   ...:     reactions = e1.as_reactions(kf=R1f) + e3.as_reactions(kf=R3f)
   ...:     return ReactionSystem(reactions, (E, A, P, X))
   ...: 

In [5]: rsys = mono_rev_single()

In [6]: rode = get_odesys(rsys)[0]

In [7]: rode.params
Out[7]: array([], dtype=object)

In [8]: rsys
Out[8]: <chempy.chemistry.ReactionSystem at 0x7f5f430d1be0>

In [9]: rsys.rxns
Out[9]: 
[<chempy.chemistry.Reaction at 0x7f5f430d1748>,
 <chempy.chemistry.Reaction at 0x7f5f430d1208>,
 <chempy.chemistry.Reaction at 0x7f5f430d1e48>,
 <chempy.chemistry.Reaction at 0x7f5f430d17b8>]

In [10]: rode = get_odesys(rsys, include_params=False)[0]

In [11]: rode.params
Out[11]: array([], dtype=object)

In [12]: rode.get_jac()
Out[12]: 
Matrix([
[-R_1f*y_1 - R_3f*y_2/R_3, -R_1f*y_0, -R_3f*y_0/R_3,  R_3f + 1.0*R_1f/R_1],
[               -R_1f*y_1, -R_1f*y_0,             0,         1.0*R_1f/R_1],
[           -R_3f*y_2/R_3,         0, -R_3f*y_0/R_3,                 R_3f],
[ R_1f*y_1 + R_3f*y_2/R_3,  R_1f*y_0,  R_3f*y_0/R_3, -R_3f - 1.0*R_1f/R_1]])
```
so this might be considered a bug in ChemPy (`include_params=False` should leave parameter in `rode.params`).

So there is still something not quite right here (since params are not filled in). I usually don't provide the SymPy symbols directly but use an internal object called `Expr`. I should eventually support using SymPy symbols directly so let's leave this issue open.

I am currently working on `get_odesys` in #40 so it's a bit of a moving target but I try very hard not
to break any tests so code shouldn't break anyway even if the syntax might be a little clunky at the moment.

To make this work right now using the `master` branch, the easiest way is to write the system directly from `Reaction` instances:
```
import sympy as sp
from chempy.chemistry import Substance, Reaction, ReactionSystem
from chempy.kinetics.ode import get_odesys
from chempy.kinetics.rates import MassAction

def mono_rev_single():
    '''Reversible mechanism with one central complex (pg 36)
    '''
    R1f, R3f, R1b, R3b = [MassAction((0,), unique_keys=(k,)) for k in 'R1f R3f R1b R3b'.split()]
    E, A, P, X = map(Substance, 'EAPX')
    reactions = [
        Reaction({'E', 'A'}, {'X'}, param=R1f),
        Reaction({'X'}, {'E', 'A'}, param=R1b),
        Reaction({'X'}, {'E', 'P'}, param=R3f),
        Reaction({'E', 'P'}, {'X'}, param=R3b)
    ]
    return ReactionSystem(reactions, (E, A, P, X))

rsys = mono_rev_single()
rode = get_odesys(rsys, include_params=False)[0]
xout, yout, info = rode.integrate(30, [1, 1, 0, 0], {'R1f': 2, 'R1b': 3, 'R3f': 4, 'R3b': 5}, integrator='cvode', atol=1e-10, rtol=1e-11)
assert info['success']
_ = rode.plot_result()
```
The argument to MassAction `(0,)` is not needed once I merge #40.

Eventually I'd like to support DAE systems (where one mixes `Reaction` instances and `Equilibrium` instances), but I need to write a wrapper around IDA in sundials for that (in analogy to my wrapper [pycvodes](https://github.com/bjodah/pycvodes) around CVode in sundials), but that is beside the point here.

**Comment by smsaladi** [comment]
@bjodah Thanks very much for the clarification. This is very helpful -- both in terms of the API and making me better consider how I am approaching my problem. I look forward to support for DAE systems in the future where one could mix `Reaction` and `Equilibrium` instances. That would be pretty useful.

**Comment by smsaladi** [comment]
Also, +1 for providing Sympy symbols directly!

**Comment by bjodah** [comment]
@smsaladi user defined parameter symbols now work in the branch for PR #40 

Here is a rendered jupyter notebook from the CI server if you're interested:
http://hera.physchem.kth.se/~chempy/branches/updated-kinets/examples/_ode_system_sympy_symbols.html

**Comment by smsaladi** [comment]
Wonderful, this is great! Thank you!
