### ISSUE TITLE
beginners question on sympy/chempy

### ISSUE THREAD

**Issue by benbowen** [bjodah/chempy#67]
I am getting started learning how to implement chempy into some of our metabolomics workflows and have hit an area where I need to learn more.  I'm looking for direction in how to best evaluate the output of balance_stoichiometry.

For this scenario:

```
balance_stoichiometry({u'C7H5O3-', u'O2', u'C21H27N7O14P2-2', u'H+'},
           {u'C7H5O4-', u'C21H26N7O14P2-', u'H2O'})
```

The following is returned:

```
({u'C21H27N7O14P2-2': x1, u'C7H5O3-': 2, u'H+': x1, u'O2': x1/2 + 1},
 {u'C21H26N7O14P2-': x1, u'C7H5O4-': 2, u'H2O': x1})
```

Looking at the dtypes, I see that they are SymPy types:

```
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.Integer'>
<class 'sympy.core.symbol.Symbol'>
```

And quickly heading over to SymPy, it seems that there is a great deal of things you can do regarding SymPy expressions, evaluations, and substitutions.

I'm looking to convert these coefficients into a SymPy expression and find the solution that satisfies the requirement that all coefficients are integers.  My naive idea is to make a SymPy expression and eval it for x1:=[1:Inf] until equality.

In the example above, x1 would be equal to 2.

I'm guessing that you have an excellent way to do this that is better than my idea, but its not immediately coming to me.  Any help is much appreciated.

**Comment by bjodah** [comment]
Hi @benbowen,

Glad to hear from you, any feedback is much appreciated. Yes, SymPy is a large library indeed.

I recently added the keyword argument `underdetermined` to `balance_stoichiometry`:
http://bjodah.github.io/chempy/latest/chempy.html#chempy.chemistry.balance_stoichiometry

My idea was that if a user sets it to `False` it would disallow (raise an error) under-determined systems. And setting it to `True` (the default) would give the linear degrees of freedoms as SymPy symbols, and setting it to `1` would return an explicit balancing with integer coefficients of minimum magnitude.

When I pass `underdetermined=1` for your system I get this answer:
```
>>> balance_stoichiometry({u'C7H5O3-', u'O2', u'C21H27N7O14P2-2', u'H+'}, {u'C7H5O4-', u'C21H26N7O14P2-', u'H2O'}, underdetermined=1)
({'C21H27N7O14P2-2': 4, 'O2': 3, 'C7H5O3-': 2, 'H+': 4}, {'C21H26N7O14P2-': 4, 'H2O': 4, 'C7H5O4-': 2})
```
so it seems that ChemPy to set `x1 == 4` instead of `x1 == 2` which supposedly is the smallest integer giving integer coefficients here.

So it looks like there is a bug (although somewhat benign). I'll look into it! I also see that the documentation of that function is not quite accurate with respect to `underdetermined`, I'll try to clarify that as well.

**Comment by benbowen** [comment]
Thanks Björn! I think 4 is the right answer and my mental calc was wrong.  underdetermined works perfectly.  I'm all set!

**Comment by bjodah** [comment]
@benbowen are you sure? If `x1 == 2` then **all** coefficients are 2 (and can hence be divided by 2, giving all coefficients equal to unity?). I'll be opening up a pull-request shortly, I'll mention you in it so that you get notified.

**Comment by benbowen** [comment]
For what its worth, this is how I ended up implementing balance_stoichiometry your thoughts would be appreciated:

```
    lhs = []
    rhs = []   
    for cpds in rxn.left_compounds:
        lhs.append(cpds.compound.formula)
    for cpds in rxn.right_compounds:
        rhs.append(cpds.compound.formula)
    
    try:
        # an incompletely defined molecule will have empty string for formula
        if min([len(f) for f in lhs+rhs]) > 0:
            if set(lhs) == set(rhs):
                # isomerization reactions etc are identical
                for cpds in rxn.left_compounds:
                    cpds.coefficient = 1
                for cpds in rxn.right_compounds:
                    cpds.coefficient = 1
                rxn.balanced = True
            else:
                b_lhs,b_rhs = balance_stoichiometry(set(lhs),set(rhs),underdetermined=1)
                for k,v in b_lhs.items():
                    if v>1:
                        for cpds in rxn.left_compounds:
                            if k == cpds.compound.formula:
                                cpds.coefficient = v
                for k,v in b_rhs.items():
                    if v>1:
                        for cpds in rxn.right_compounds:
                            if k == cpds.compound.formula:
                                cpds.coefficient = v
                rxn.balanced = True
                balanced += 1
        else:
            # There are undefined molecules in this equation
            rxn.balanced = False
            undefined += 1
    except:
        # The system can not be simplified into integer coefficients
        rxn.balanced = False
        illogical += 1
```

**Comment by bjodah** [comment]
Looks alright to me.
